// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Nars_struct = require("./nars_struct.bs.js");
var Reader$Ocamlprotocplugin = require("ocaml-protoc-plugin-runtime-bs/src/ocaml_protoc_plugin/reader.bs.js");
var Writer$Ocamlprotocplugin = require("ocaml-protoc-plugin-runtime-bs/src/ocaml_protoc_plugin/writer.bs.js");

Curry._1(Nars_struct.Google_mirror.Protobuf.Struct.from_proto, (function (eta) {
          return Reader$Ocamlprotocplugin.create(undefined, undefined, eta);
        })(Writer$Ocamlprotocplugin.contents(Curry._1(Nars_struct.Google_mirror.Protobuf.Struct.to_proto, /* :: */[
                  /* tuple */[
                    "fieldA",
                    /* `Number_value */[
                      -785426853,
                      1
                    ]
                  ],
                  /* :: */[
                    /* tuple */[
                      "fieldB",
                      /* `Bool_value */[
                        258787964,
                        true
                      ]
                    ],
                    /* [] */0
                  ]
                ]))));

/*  Not a pure module */
